### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Cozy888** [KudoAI/bravegpt#11]
It worked for a few weeks then it stop. Installed violentmonkey to see if it was tampermonkey fault but nope.
![Sem Título](https://github.com/KudoAI/bravegpt/assets/95589456/9f9faeb6-97fa-484c-93ad-5a4ea5fbdd7b)

**Comment by adamlui** [comment]
Hey @Cozy888 thanks for reporting, they changed the HTML so it broke but is now fixed, can you update to 2023.9.6 @ https://bravegpt.com/greasyfork

**Comment by Cozy888** [comment]
I updated and didn't work, it said to use the Proxy Mode and when i switch to Proxy Mode the box dissapears.
Keep up the good work!

**Comment by Cozy888** [comment]
I updated and it works barely with and without proxy mode and u can't see the letter on the text box
Keep up the good work !
![111](https://github.com/KudoAI/bravegpt/assets/95589456/b4196c5d-e2ef-41d1-904c-daf0c358cd20)

**Comment by adamlui** [comment]
@Cozy888 thank you for the screenshot, what method do you use to make it dark mode?

**Comment by Cozy888** [comment]
Oh it supposed to be like that ? I didn't to do nothing sometimes appears like that and sometimes in dark mode but it doesn't show the full text well.
![w](https://github.com/KudoAI/bravegpt/assets/95589456/360d713b-80e5-487f-8a9f-737a116c11cc)

**Comment by adamlui** [comment]
@Cozy888 before I didn't have to code in the styles before Brave removed a container that contained special classes, so now it's unreliable. What is your browser and how did you set dark mode?

**Comment by adamlui** [comment]
@Cozy888 the latest version @ https://bravegpt.com/greasyfork v2023.9.7 now has the dark mode styles hard-coded, but I couldn't replicate your last screenshot where it's cut off, could you tell me what your browser and userscript manager is?

**Comment by Cozy888** [comment]
I updated to the latest version but now it doesn't work, i use brave and violentmonkey
I had my theme on brave in dark mode, could be that ?
![33](https://github.com/KudoAI/bravegpt/assets/95589456/ca75a18c-22ca-4fb8-9621-5f201cbf702c)

**Comment by adamlui** [comment]
Thank you for the screenshot @cozy888! I wil investigate this immediately now

**Comment by adamlui** [comment]
@Cozy888 thank you again for your excellent feedback, I have resolved both issues now, can you please update to v2023.9.9.2 @ [https://bravegpt.com/greasyfork](https://bravegpt.com/greasyfork)

**Comment by Cozy888** [comment]
Working perfectly !! I appreciate your efforts and I hope you'll keep excelling in your work !
![qqqq](https://github.com/KudoAI/bravegpt/assets/95589456/b632a8e1-068d-43a7-aa28-f0d0cb633bd8)

**Comment by adamlui** [comment]
Thanks @Cozy888 if you want you could leave a review @ https://greasyfork.org/en/scripts/462440-bravegpt/feedback#post-discussion
