### ISSUE TITLE
Error loading dependencies

### ISSUE THREAD

**Issue by Cozy888** [KudoAI/bravegpt#15]
I received a notification saying i had to install or reinstall bravegpt, so i tried and i got this.
![www](https://github.com/KudoAI/bravegpt/assets/95589456/8b6c90ef-9ddb-4508-b01b-810977c40ce9)

**Comment by adamlui** [comment]
@Cozy888 thank you for pointing out this error, it is fixed now can you update to v2023.10.12.1 @ https://bravegpt.com/greasyfork

**Comment by adamlui** [comment]
@Cozy888 also can I have your opinion? Which URL do you find more memorable or easy to type:

1. https://bravegpt.com/greasyfork
2. https://greasyfork.bravegpt.com

**Comment by Cozy888** [comment]
I prefer "https://greasyfork.bravegpt.com/"
